### ISSUE TITLE
Combination with A570 and "2MB RAM for A570"

### ISSUE THREAD

**Issue by StefanKrupop** [LIV2/GottaGoFastRAM#10]
Dear LIV2,

thank you for this project! I built one and it seems to be working fine so far (just finished it).

I am using an A570 (together with a [Vector Falcon 570](http://amiga.resource.cx/expde/falcon570)) and tied CFGIN of the GottaGoFastRAM to Pin 11 on the A500 expansion connector, so it will get asserted after the DMAC in the A570 is configured. Seems to be ok, I see 2 MB Chip and 8 MB Fast.

However, I previously had a [2MB RAM for A570](http://amiga.resource.cx/expde/2mb570) expansion in the A570 as well, providing 2 MB of Fast RAM.
I now had to remove it to get the full 8 MB provided by the GottaGoFastRAM. With it installed the Amiga sees just 6 MB of Fast RAM.

I wonder whether it would be possible to use both expansions simultaneously, giving a total of 10 MB Fast RAM? The 2 MB RAM in the A570 seem to be mapped to 0x200000.

Kind regards,
Stefan

**Comment by LIV2** [comment]
Hi Stefan,

Unfortunately it's not possible for this board to provide memory outside of the 8MB Autoconfig memory space as that would require the use of 2 more pins on the CPLD which is already maxed out. so it would not be possible to get 10MB this way.

To make it coexist better with the 570 Ram expansion you could try the [Experimental firmware](https://github.com/LIV2/GottaGoFastRAM/tree/snoopy/Binaries/experimental) which would allow the GGF board to completely fill up the remaining ram space giving you 8MB total fastram even with the 570 and it's 2MB expansion.
If you go down that path please let me know how it goes

**Comment by StefanKrupop** [comment]
Thank you for the quick reply!

I would have thought that 8  MB AutoConfig would be fine, as the 2 MB are also AutoConfig'ed (at least I think that). Or does the A500 just have one 8 MB Autoconfig memory space that is shared between all expansions?

This is what the "Expansion Board Diagnostic" (Holding both mouse buttons on boot) shows for the different configurations:

GGF and A570, no 2 MB-Expansion:
| Board Number | Manufacturer | Product | Status |
| ------------ | ------------ | ------- | ------ |
| 1 | 514 | 3 | Working |
| 2 | 2011 | 69 | Working |

Gives Fastmem from 0x200000 to 0x9fffff.

A570 with 2 MB-Expansion, no GGF:
| Board Number | Manufacturer | Product | Status |
| ------------ | ------------ | ------- | ------ |
| 1 | 514 | 3 | Working |
| 2 | 514 | 10 | Working |

Gives Fastmem from 0x200000 to 0x3fffff.

GGF and A570 with 2 MB-Expansion:
| Board Number | Manufacturer | Product | Status |
| ------------ | ------------ | ------- | ------ |
| 1 | 514 | 3 | Working |
| 2 | 514 | 10 | Working |
| 3 | 2011 | 69 | Defective |
| 4 | 2011 | 69 | Working |

Gives Fastmem from 0x200000 to 0x3fffff and 0x600000 to 0x9fffff.

Shouldn't the Autoconfig process simply map the GGF behind the 2 MB of the A650, starting at 0x400000?

Kind regards,
Stefan

**Comment by StefanKrupop** [comment]
Never mind. I found an address map for the A500 and indeed, just 0x200000 - 0x9fffff is reserved for Autoconfig, 0xa00000 - 0xbeffff is "reserved". So not more than 8 MB possible via Autoconfigured expansions...

**Comment by LIV2** [comment]
> I would have thought that 8 MB AutoConfig would be fine, as the 2 MB are also AutoConfig'ed (at least I think that). Or does the A500 just have one 8 MB Autoconfig memory space that is shared between all expansions?

Yes Zorro expansions all share the 8MB Block of 0x200000 - 0x9FFFFF so the maximum amount of fast ram is 8MB

> Shouldn't the Autoconfig process simply map the GGF behind the 2 MB of the A650, starting at 0x400000?

Kickstart maps 2MB blocks on 2MB boundaries, 4MB on 4MB boundaries etc which is why this doesn't happen unfortunately - it probably would have complicated address decoding for boards back in the day I guess.


Due to kickstart bugs it is not usually possible for the board to 6MB with this autosizing trick, it can cause yellow screen errors.
The Experimental firmware though sniffs autoconfig cycles for other devices and resizes it's offering in 2MB chunks to match & fill up the remaining space, so this should give you the full 8MB even with the A570's 2MB installed
