### ISSUE TITLE
No FastRAM detected A500 rev6a KS3.1.4

### ISSUE THREAD

**Issue by krug3rf** [LIV2/GottaGoFastRAM#11]
Hi everyone and happy new year ^^

I build the last rev of the PCB with the revb firmware.
The A500 (with 1MB on the motherboard, not an extension) start but the FastRAM stuck at 0MB (AmigaTestKit, Diagrom, etc.)

What I tested, but no effect ;(

- replace the Xilinx (twice),
- replace the DRAM TSSOP twice (_samsung K4E641612D in my case_),
- remove the additional 512kb,
- replace the KS by an 1.3

Are you aware about this kind of issue  ?

**Comment by LIV2** [comment]
Hi,

This should work with your system and has been tested in a rev6a but I'm not yet sure why it doesn't work for you.

Can you please take a photo of the PCB and attach it to this issue?

**Comment by krug3rf** [comment]
I just finish a last check, but stuck with 0MB

- reflow U6 and U7
- test on another rev6a
![IMG_20230113_232239](https://user-images.githubusercontent.com/77207351/212432904-d381118d-dd39-40e7-b89b-3620484c380d.jpg)
![IMG_20230113_232259](https://user-images.githubusercontent.com/77207351/212432912-58fd0f61-20f3-47db-9a88-358f4826d09a.jpg)
![IMG_20230113_232309](https://user-images.githubusercontent.com/77207351/212432916-acddc93c-26fe-45ae-a4c6-f522fcb08eca.jpg)
![IMG_20230113_232316](https://user-images.githubusercontent.com/77207351/212432920-05b8e3eb-0648-4072-850e-a9012c46aa52.jpg)
![IMG_20230113_232321](https://user-images.githubusercontent.com/77207351/212432922-11f701bb-eb29-4cde-9bb8-5656eb55142c.jpg)
![IMG_20230113_232329](https://user-images.githubusercontent.com/77207351/212432924-7ce10753-cb28-48fc-82d4-d14a4e042574.jpg)
![IMG_20230113_232342](https://user-images.githubusercontent.com/77207351/212432925-98472d3c-7d10-4d25-9e81-27c86a780c88.jpg)

**Comment by krug3rf** [comment]
And the impact.log 
[_impact.log](https://github.com/LIV2/GottaGoFastRAM/files/10415924/_impact.log)

**Comment by LIV2** [comment]
It looks like the solder joint of U4 pin 1 might be bad, if you haven't already reflowed that chip please do so.

If you have an oscilloscope you will want to probe pin 1 and 6 of U4 where you should see a 7Mhz clock signal on both pins, if this isn't working it would explain what you're experiencing.

If U4 is bad you can remove it and close the 2 solder jumpers on the bottom to bypass it, the board may be more reliable with U4 fitted though

**Comment by krug3rf** [comment]
Thx for advise, I don't have an oscilloscope, so...

_"If U4 is bad you can remove it and close the 2 solder jumpers on the bottom to bypass it, the board may be more reliable with U4 fitted though"_

Do you talking about J2 and J3 ?

**Comment by LIV2** [comment]
Yep those are the ones you will want to close.

**Comment by krug3rf** [comment]
After two reflow on U4, bazinga !
Thx for your help !
![IMG_20230114_221049](https://user-images.githubusercontent.com/77207351/212497317-02682a05-f48c-40ca-bfdc-feb6de5290e6.jpg)
