### ISSUE TITLE
5V or 3.3V ram?

### ISSUE THREAD

**Issue by RetepV** [LIV2/GottaGoFastRAM#14]
I wanted to make some of these boards and was checking out the ram options. And then I noticed that some 4Mx16 rams have 5V VCC, while others have 3.3V VCC. Looking at the schematics, it seems the ram chip is fed with 5V VCC.

You are recommending K4E641612D or GM71VS65163, but these are both 3.3V parts as far as I can see. Also, the Micron MT4LC4M16R6 that I wrote about earlier is a 3.3V part.

In your 'assembled.jpg' image, I see a GM71VS65163CLT-5, which is a 3.3V part. But in your 'stacked1.jpg' image, I see that you used a KM416LC4104AS-6 chip, and that is a 5V part according to the datasheet.

Schematic.pdf for both revision A and B1 show that the ram is fed with 5V. But 5V would destroy a 3.3V ram, imo. So how are you handling that difference?

**Comment by RetepV** [comment]
Oh crap, I read the schematics wrong. My fault! I see that the rams ARE actually fed with the 3.3V, so we need 3.3V rams.

I'll close this issue because it's still a warning that the KM416LC4104AS-6 is a 5V chip according to the datasheet. I can't imagine that it would work reliably when fed with 3.3V.

Cheers!

**Comment by LIV2** [comment]
Yep on Rev A the RAM is a 5V part supplied with 5V - this was changed to a 3.3V part in Rev B because at the time it was cheaper and easier to get 3.3V parts

The stacked configuration is shown with a Rev A, I will have to make a note on the page about htat

**Comment by RetepV** [comment]
👍
