### ISSUE TITLE
schematic pdf

### ISSUE THREAD

**Issue by kipper2k** [LIV2/GottaGoFastRAM#2]
Hi,  Great design, i like the 1x8MB ram chip.  I have made a A500 IDE board with CF header and would like to add this fastmem design to it, Do you have  a schematic pdf available for sharing or eagle cad files ?

Thanks.  Brian.

**Comment by LIV2** [comment]
Hi Brian,

Thanks, this board was designed with Altium CircuitMaker but the schematics are available here: https://github.com/LIV2/GottaGoFastRAM/blob/master/Schematic.pdf

Do you have a link to your project? It sounds good I'd love to get my hands on one when it is released :)
